import img1 from "../../../../assets/images/hom2.jpg";
import img2 from "../../../../assets/images/home.jpg";
const properties = [
  {
    id: 1,
    image: img1,
    price: "$235,000",
    bedrooms: 3,
    bathrooms: 1,
    size: 960,
    status: "House for sale",
    address: "4006 Little Mountain Rd, Gastonia, NC 28056",
    type: "Single Family Residence",
    yearBuilt: 1963,
    heating: "Forced Air, Natural Gas",
    cooling: "Ceiling Fan(s), Central Air",
    parking: "1 Carport space",
    lot: "0.40 Acres",
    pricePerSqft: "$245",
  },
  {
    id: 2,
    image: img2,
    price: "$350,000",
    bedrooms: 4,
    bathrooms: 2,
    size: 1800,
    status: "House for sale",
    address: "1234 Main St, Anytown, USA",
    type: "Single Family Residence",
    yearBuilt: 2005,
    heating: "Central Heat, Electric",
    cooling: "Central Air",
    parking: "2 Car Garage",
    lot: "0.25 Acres",
    pricePerSqft: "$194",
  },
  {
    id: 3,
    image: img1,
    price: "$500,000",
    bedrooms: 5,
    bathrooms: 3.5,
    size: 3000,
    status: "House for sale",
    address: "5678 Elm St, Smalltown, USA",
    type: "Single Family Residence",
    yearBuilt: 2010,
    heating: "Radiant Heat, Gas",
    cooling: "Central Air",
    parking: "3 Car Garage",
    lot: "0.50 Acres",
    pricePerSqft: "$167",
  },
];

export default properties;
